// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benx421/payment-gateway/bank/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx
func (_m *MockTransactionRepository) Create(ctx context.Context, tx *models.Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *models.Transaction
func (_e *MockTransactionRepository_Expecter) Create(ctx interface{}, tx interface{}) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, tx *models.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(_a0 error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Transaction) error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTransactionRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTransactionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTransactionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTransactionRepository_FindByID_Call {
	return &MockTransactionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTransactionRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) Return(_a0 *models.Transaction, _a1 error) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Transaction, error)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDForUpdate provides a mock function with given fields: ctx, id
func (_m *MockTransactionRepository) FindByIDForUpdate(ctx context.Context, id uuid.UUID) (*models.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDForUpdate")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_FindByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDForUpdate'
type MockTransactionRepository_FindByIDForUpdate_Call struct {
	*mock.Call
}

// FindByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTransactionRepository_Expecter) FindByIDForUpdate(ctx interface{}, id interface{}) *MockTransactionRepository_FindByIDForUpdate_Call {
	return &MockTransactionRepository_FindByIDForUpdate_Call{Call: _e.mock.On("FindByIDForUpdate", ctx, id)}
}

func (_c *MockTransactionRepository_FindByIDForUpdate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTransactionRepository_FindByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByIDForUpdate_Call) Return(_a0 *models.Transaction, _a1 error) *MockTransactionRepository_FindByIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_FindByIDForUpdate_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Transaction, error)) *MockTransactionRepository_FindByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindByReferenceID provides a mock function with given fields: ctx, refID, txnType
func (_m *MockTransactionRepository) FindByReferenceID(ctx context.Context, refID uuid.UUID, txnType models.TransactionType) (*models.Transaction, error) {
	ret := _m.Called(ctx, refID, txnType)

	if len(ret) == 0 {
		panic("no return value specified for FindByReferenceID")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.TransactionType) (*models.Transaction, error)); ok {
		return rf(ctx, refID, txnType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.TransactionType) *models.Transaction); ok {
		r0 = rf(ctx, refID, txnType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.TransactionType) error); ok {
		r1 = rf(ctx, refID, txnType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_FindByReferenceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByReferenceID'
type MockTransactionRepository_FindByReferenceID_Call struct {
	*mock.Call
}

// FindByReferenceID is a helper method to define mock.On call
//   - ctx context.Context
//   - refID uuid.UUID
//   - txnType models.TransactionType
func (_e *MockTransactionRepository_Expecter) FindByReferenceID(ctx interface{}, refID interface{}, txnType interface{}) *MockTransactionRepository_FindByReferenceID_Call {
	return &MockTransactionRepository_FindByReferenceID_Call{Call: _e.mock.On("FindByReferenceID", ctx, refID, txnType)}
}

func (_c *MockTransactionRepository_FindByReferenceID_Call) Run(run func(ctx context.Context, refID uuid.UUID, txnType models.TransactionType)) *MockTransactionRepository_FindByReferenceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.TransactionType))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByReferenceID_Call) Return(_a0 *models.Transaction, _a1 error) *MockTransactionRepository_FindByReferenceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_FindByReferenceID_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.TransactionType) (*models.Transaction, error)) *MockTransactionRepository_FindByReferenceID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockTransactionRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status models.TransactionStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.TransactionStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTransactionRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status models.TransactionStatus
func (_e *MockTransactionRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockTransactionRepository_UpdateStatus_Call {
	return &MockTransactionRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockTransactionRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status models.TransactionStatus)) *MockTransactionRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.TransactionStatus))
	})
	return _c
}

func (_c *MockTransactionRepository_UpdateStatus_Call) Return(_a0 error) *MockTransactionRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.TransactionStatus) error) *MockTransactionRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
