// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benx421/payment-gateway/bank/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// AdjustBalances provides a mock function with given fields: ctx, accountID, balanceDelta, availableBalanceDelta
func (_m *MockAccountRepository) AdjustBalances(ctx context.Context, accountID uuid.UUID, balanceDelta int64, availableBalanceDelta int64) error {
	ret := _m.Called(ctx, accountID, balanceDelta, availableBalanceDelta)

	if len(ret) == 0 {
		panic("no return value specified for AdjustBalances")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, int64) error); ok {
		r0 = rf(ctx, accountID, balanceDelta, availableBalanceDelta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_AdjustBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustBalances'
type MockAccountRepository_AdjustBalances_Call struct {
	*mock.Call
}

// AdjustBalances is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
//   - balanceDelta int64
//   - availableBalanceDelta int64
func (_e *MockAccountRepository_Expecter) AdjustBalances(ctx interface{}, accountID interface{}, balanceDelta interface{}, availableBalanceDelta interface{}) *MockAccountRepository_AdjustBalances_Call {
	return &MockAccountRepository_AdjustBalances_Call{Call: _e.mock.On("AdjustBalances", ctx, accountID, balanceDelta, availableBalanceDelta)}
}

func (_c *MockAccountRepository_AdjustBalances_Call) Run(run func(ctx context.Context, accountID uuid.UUID, balanceDelta int64, availableBalanceDelta int64)) *MockAccountRepository_AdjustBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockAccountRepository_AdjustBalances_Call) Return(_a0 error) *MockAccountRepository_AdjustBalances_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_AdjustBalances_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64, int64) error) *MockAccountRepository_AdjustBalances_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAccountNumber provides a mock function with given fields: ctx, accountNumber
func (_m *MockAccountRepository) FindByAccountNumber(ctx context.Context, accountNumber string) (*models.Account, error) {
	ret := _m.Called(ctx, accountNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindByAccountNumber")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Account, error)); ok {
		return rf(ctx, accountNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Account); ok {
		r0 = rf(ctx, accountNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_FindByAccountNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAccountNumber'
type MockAccountRepository_FindByAccountNumber_Call struct {
	*mock.Call
}

// FindByAccountNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNumber string
func (_e *MockAccountRepository_Expecter) FindByAccountNumber(ctx interface{}, accountNumber interface{}) *MockAccountRepository_FindByAccountNumber_Call {
	return &MockAccountRepository_FindByAccountNumber_Call{Call: _e.mock.On("FindByAccountNumber", ctx, accountNumber)}
}

func (_c *MockAccountRepository_FindByAccountNumber_Call) Run(run func(ctx context.Context, accountNumber string)) *MockAccountRepository_FindByAccountNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountRepository_FindByAccountNumber_Call) Return(_a0 *models.Account, _a1 error) *MockAccountRepository_FindByAccountNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_FindByAccountNumber_Call) RunAndReturn(run func(context.Context, string) (*models.Account, error)) *MockAccountRepository_FindByAccountNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAccountNumberForUpdate provides a mock function with given fields: ctx, accountNumber
func (_m *MockAccountRepository) FindByAccountNumberForUpdate(ctx context.Context, accountNumber string) (*models.Account, error) {
	ret := _m.Called(ctx, accountNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindByAccountNumberForUpdate")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Account, error)); ok {
		return rf(ctx, accountNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Account); ok {
		r0 = rf(ctx, accountNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_FindByAccountNumberForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAccountNumberForUpdate'
type MockAccountRepository_FindByAccountNumberForUpdate_Call struct {
	*mock.Call
}

// FindByAccountNumberForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNumber string
func (_e *MockAccountRepository_Expecter) FindByAccountNumberForUpdate(ctx interface{}, accountNumber interface{}) *MockAccountRepository_FindByAccountNumberForUpdate_Call {
	return &MockAccountRepository_FindByAccountNumberForUpdate_Call{Call: _e.mock.On("FindByAccountNumberForUpdate", ctx, accountNumber)}
}

func (_c *MockAccountRepository_FindByAccountNumberForUpdate_Call) Run(run func(ctx context.Context, accountNumber string)) *MockAccountRepository_FindByAccountNumberForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountRepository_FindByAccountNumberForUpdate_Call) Return(_a0 *models.Account, _a1 error) *MockAccountRepository_FindByAccountNumberForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_FindByAccountNumberForUpdate_Call) RunAndReturn(run func(context.Context, string) (*models.Account, error)) *MockAccountRepository_FindByAccountNumberForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockAccountRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAccountRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAccountRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockAccountRepository_FindByID_Call {
	return &MockAccountRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockAccountRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAccountRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAccountRepository_FindByID_Call) Return(_a0 *models.Account, _a1 error) *MockAccountRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Account, error)) *MockAccountRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
