// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for AuthorizationResponseStatus.
const (
	Approved AuthorizationResponseStatus = "approved"
)

// Defines values for CaptureResponseStatus.
const (
	Captured CaptureResponseStatus = "captured"
)

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyCaptured          ErrorCode = "already_captured"
	ErrorCodeAlreadyRefunded          ErrorCode = "already_refunded"
	ErrorCodeAlreadyVoided            ErrorCode = "already_voided"
	ErrorCodeAmountMismatch           ErrorCode = "amount_mismatch"
	ErrorCodeAuthorizationAlreadyUsed ErrorCode = "authorization_already_used"
	ErrorCodeAuthorizationExpired     ErrorCode = "authorization_expired"
	ErrorCodeAuthorizationNotFound    ErrorCode = "authorization_not_found"
	ErrorCodeCaptureNotFound          ErrorCode = "capture_not_found"
	ErrorCodeCardExpired              ErrorCode = "card_expired"
	ErrorCodeInsufficientFunds        ErrorCode = "insufficient_funds"
	ErrorCodeInternalError            ErrorCode = "internal_error"
	ErrorCodeInvalidAmount            ErrorCode = "invalid_amount"
	ErrorCodeInvalidCard              ErrorCode = "invalid_card"
	ErrorCodeInvalidCvv               ErrorCode = "invalid_cvv"
	ErrorCodeMissingIdempotencyKey    ErrorCode = "missing_idempotency_key"
	ErrorCodeNotFound                 ErrorCode = "not_found"
	ErrorCodeRefundNotFound           ErrorCode = "refund_not_found"
)

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for RefundResponseStatus.
const (
	Refunded RefundResponseStatus = "refunded"
)

// Defines values for VoidResponseStatus.
const (
	Voided VoidResponseStatus = "voided"
)

// AuthorizationResponse defines model for AuthorizationResponse.
type AuthorizationResponse struct {
	Amount          int64                       `json:"amount"`
	AuthorizationId string                      `json:"authorization_id"`
	CreatedAt       time.Time                   `json:"created_at"`
	Currency        string                      `json:"currency"`
	ExpiresAt       time.Time                   `json:"expires_at"`
	Status          AuthorizationResponseStatus `json:"status"`
}

// AuthorizationResponseStatus defines model for AuthorizationResponse.Status.
type AuthorizationResponseStatus string

// CaptureResponse defines model for CaptureResponse.
type CaptureResponse struct {
	Amount          int64                 `json:"amount"`
	AuthorizationId string                `json:"authorization_id"`
	CaptureId       string                `json:"capture_id"`
	CapturedAt      time.Time             `json:"captured_at"`
	Currency        string                `json:"currency"`
	Status          CaptureResponseStatus `json:"status"`
}

// CaptureResponseStatus defines model for CaptureResponse.Status.
type CaptureResponseStatus string

// CreateAuthorizationRequest defines model for CreateAuthorizationRequest.
type CreateAuthorizationRequest struct {
	// Amount Amount in cents
	Amount int64 `json:"amount"`

	// CardNumber Card number (Luhn validated)
	CardNumber string `json:"card_number"`

	// Cvv Card verification value
	Cvv         string `json:"cvv"`
	ExpiryMonth int    `json:"expiry_month"`
	ExpiryYear  int    `json:"expiry_year"`
}

// CreateCaptureRequest defines model for CreateCaptureRequest.
type CreateCaptureRequest struct {
	// Amount Amount in cents (must match authorization)
	Amount int64 `json:"amount"`

	// AuthorizationId Authorization ID to capture
	AuthorizationId string `json:"authorization_id"`
}

// CreateRefundRequest defines model for CreateRefundRequest.
type CreateRefundRequest struct {
	// Amount Amount in cents (must match capture)
	Amount int64 `json:"amount"`

	// CaptureId Capture ID to refund
	CaptureId string `json:"capture_id"`
}

// CreateVoidRequest defines model for CreateVoidRequest.
type CreateVoidRequest struct {
	// AuthorizationId Authorization ID to void
	AuthorizationId string `json:"authorization_id"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   ErrorCode `json:"error"`
	Message string    `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// RefundResponse defines model for RefundResponse.
type RefundResponse struct {
	Amount     int64                `json:"amount"`
	CaptureId  string               `json:"capture_id"`
	Currency   string               `json:"currency"`
	RefundId   string               `json:"refund_id"`
	RefundedAt time.Time            `json:"refunded_at"`
	Status     RefundResponseStatus `json:"status"`
}

// RefundResponseStatus defines model for RefundResponse.Status.
type RefundResponseStatus string

// VoidResponse defines model for VoidResponse.
type VoidResponse struct {
	AuthorizationId string             `json:"authorization_id"`
	Status          VoidResponseStatus `json:"status"`
	VoidId          string             `json:"void_id"`
	VoidedAt        time.Time          `json:"voided_at"`
}

// VoidResponseStatus defines model for VoidResponse.Status.
type VoidResponseStatus string

// AuthorizationId defines model for AuthorizationId.
type AuthorizationId = string

// CaptureId defines model for CaptureId.
type CaptureId = string

// IdempotencyKeyRequired defines model for IdempotencyKeyRequired.
type IdempotencyKeyRequired = string

// RefundId defines model for RefundId.
type RefundId = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PaymentRequired defines model for PaymentRequired.
type PaymentRequired = ErrorResponse

// CreateAuthorizationParams defines parameters for CreateAuthorization.
type CreateAuthorizationParams struct {
	// IdempotencyKey Unique key for idempotent requests (max 255 chars)
	IdempotencyKey IdempotencyKeyRequired `json:"Idempotency-Key"`
}

// CreateCaptureParams defines parameters for CreateCapture.
type CreateCaptureParams struct {
	// IdempotencyKey Unique key for idempotent requests (max 255 chars)
	IdempotencyKey IdempotencyKeyRequired `json:"Idempotency-Key"`
}

// CreateRefundParams defines parameters for CreateRefund.
type CreateRefundParams struct {
	// IdempotencyKey Unique key for idempotent requests (max 255 chars)
	IdempotencyKey IdempotencyKeyRequired `json:"Idempotency-Key"`
}

// CreateVoidParams defines parameters for CreateVoid.
type CreateVoidParams struct {
	// IdempotencyKey Unique key for idempotent requests (max 255 chars)
	IdempotencyKey IdempotencyKeyRequired `json:"Idempotency-Key"`
}

// CreateAuthorizationJSONRequestBody defines body for CreateAuthorization for application/json ContentType.
type CreateAuthorizationJSONRequestBody = CreateAuthorizationRequest

// CreateCaptureJSONRequestBody defines body for CreateCapture for application/json ContentType.
type CreateCaptureJSONRequestBody = CreateCaptureRequest

// CreateRefundJSONRequestBody defines body for CreateRefund for application/json ContentType.
type CreateRefundJSONRequestBody = CreateRefundRequest

// CreateVoidJSONRequestBody defines body for CreateVoid for application/json ContentType.
type CreateVoidJSONRequestBody = CreateVoidRequest
