//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create authorization hold
	// (POST /api/v1/authorizations)
	CreateAuthorization(w http.ResponseWriter, r *http.Request, params CreateAuthorizationParams)
	// Get authorization details
	// (GET /api/v1/authorizations/{authorizationId})
	GetAuthorization(w http.ResponseWriter, r *http.Request, authorizationId AuthorizationId)
	// Capture authorization
	// (POST /api/v1/captures)
	CreateCapture(w http.ResponseWriter, r *http.Request, params CreateCaptureParams)
	// Get capture details
	// (GET /api/v1/captures/{captureId})
	GetCapture(w http.ResponseWriter, r *http.Request, captureId CaptureId)
	// Refund capture
	// (POST /api/v1/refunds)
	CreateRefund(w http.ResponseWriter, r *http.Request, params CreateRefundParams)
	// Get refund details
	// (GET /api/v1/refunds/{refundId})
	GetRefund(w http.ResponseWriter, r *http.Request, refundId RefundId)
	// Void authorization
	// (POST /api/v1/voids)
	CreateVoid(w http.ResponseWriter, r *http.Request, params CreateVoidParams)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAuthorization operation middleware
func (siw *ServerInterfaceWrapper) CreateAuthorization(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateAuthorizationParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKeyRequired
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAuthorization(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthorization operation middleware
func (siw *ServerInterfaceWrapper) GetAuthorization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "authorizationId" -------------
	var authorizationId AuthorizationId

	err = runtime.BindStyledParameterWithOptions("simple", "authorizationId", r.PathValue("authorizationId"), &authorizationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "authorizationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthorization(w, r, authorizationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCapture operation middleware
func (siw *ServerInterfaceWrapper) CreateCapture(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCaptureParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKeyRequired
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCapture(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCapture operation middleware
func (siw *ServerInterfaceWrapper) GetCapture(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "captureId" -------------
	var captureId CaptureId

	err = runtime.BindStyledParameterWithOptions("simple", "captureId", r.PathValue("captureId"), &captureId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "captureId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCapture(w, r, captureId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRefund operation middleware
func (siw *ServerInterfaceWrapper) CreateRefund(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateRefundParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKeyRequired
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRefund(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRefund operation middleware
func (siw *ServerInterfaceWrapper) GetRefund(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "refundId" -------------
	var refundId RefundId

	err = runtime.BindStyledParameterWithOptions("simple", "refundId", r.PathValue("refundId"), &refundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refundId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRefund(w, r, refundId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVoid operation middleware
func (siw *ServerInterfaceWrapper) CreateVoid(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateVoidParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKeyRequired
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVoid(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1/authorizations", wrapper.CreateAuthorization)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/authorizations/{authorizationId}", wrapper.GetAuthorization)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/captures", wrapper.CreateCapture)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/captures/{captureId}", wrapper.GetCapture)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/refunds", wrapper.CreateRefund)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/refunds/{refundId}", wrapper.GetRefund)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/voids", wrapper.CreateVoid)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)

	return m
}

type BadRequestJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type PaymentRequiredJSONResponse ErrorResponse

type CreateAuthorizationRequestObject struct {
	Params CreateAuthorizationParams
	Body   *CreateAuthorizationJSONRequestBody
}

type CreateAuthorizationResponseObject interface {
	VisitCreateAuthorizationResponse(w http.ResponseWriter) error
}

type CreateAuthorization200JSONResponse AuthorizationResponse

func (response CreateAuthorization200JSONResponse) VisitCreateAuthorizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateAuthorization400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAuthorization400JSONResponse) VisitCreateAuthorizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAuthorization402JSONResponse struct{ PaymentRequiredJSONResponse }

func (response CreateAuthorization402JSONResponse) VisitCreateAuthorizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(402)

	return json.NewEncoder(w).Encode(response)
}

type CreateAuthorization500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateAuthorization500JSONResponse) VisitCreateAuthorizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthorizationRequestObject struct {
	AuthorizationId AuthorizationId `json:"authorizationId"`
}

type GetAuthorizationResponseObject interface {
	VisitGetAuthorizationResponse(w http.ResponseWriter) error
}

type GetAuthorization200JSONResponse AuthorizationResponse

func (response GetAuthorization200JSONResponse) VisitGetAuthorizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthorization404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAuthorization404JSONResponse) VisitGetAuthorizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateCaptureRequestObject struct {
	Params CreateCaptureParams
	Body   *CreateCaptureJSONRequestBody
}

type CreateCaptureResponseObject interface {
	VisitCreateCaptureResponse(w http.ResponseWriter) error
}

type CreateCapture200JSONResponse CaptureResponse

func (response CreateCapture200JSONResponse) VisitCreateCaptureResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateCapture400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateCapture400JSONResponse) VisitCreateCaptureResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateCapture500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateCapture500JSONResponse) VisitCreateCaptureResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCaptureRequestObject struct {
	CaptureId CaptureId `json:"captureId"`
}

type GetCaptureResponseObject interface {
	VisitGetCaptureResponse(w http.ResponseWriter) error
}

type GetCapture200JSONResponse CaptureResponse

func (response GetCapture200JSONResponse) VisitGetCaptureResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCapture404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCapture404JSONResponse) VisitGetCaptureResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateRefundRequestObject struct {
	Params CreateRefundParams
	Body   *CreateRefundJSONRequestBody
}

type CreateRefundResponseObject interface {
	VisitCreateRefundResponse(w http.ResponseWriter) error
}

type CreateRefund200JSONResponse RefundResponse

func (response CreateRefund200JSONResponse) VisitCreateRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateRefund400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateRefund400JSONResponse) VisitCreateRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateRefund500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateRefund500JSONResponse) VisitCreateRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRefundRequestObject struct {
	RefundId RefundId `json:"refundId"`
}

type GetRefundResponseObject interface {
	VisitGetRefundResponse(w http.ResponseWriter) error
}

type GetRefund200JSONResponse RefundResponse

func (response GetRefund200JSONResponse) VisitGetRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRefund404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRefund404JSONResponse) VisitGetRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateVoidRequestObject struct {
	Params CreateVoidParams
	Body   *CreateVoidJSONRequestBody
}

type CreateVoidResponseObject interface {
	VisitCreateVoidResponse(w http.ResponseWriter) error
}

type CreateVoid200JSONResponse VoidResponse

func (response CreateVoid200JSONResponse) VisitCreateVoidResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateVoid400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateVoid400JSONResponse) VisitCreateVoidResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateVoid500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateVoid500JSONResponse) VisitCreateVoidResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth503JSONResponse HealthResponse

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create authorization hold
	// (POST /api/v1/authorizations)
	CreateAuthorization(ctx context.Context, request CreateAuthorizationRequestObject) (CreateAuthorizationResponseObject, error)
	// Get authorization details
	// (GET /api/v1/authorizations/{authorizationId})
	GetAuthorization(ctx context.Context, request GetAuthorizationRequestObject) (GetAuthorizationResponseObject, error)
	// Capture authorization
	// (POST /api/v1/captures)
	CreateCapture(ctx context.Context, request CreateCaptureRequestObject) (CreateCaptureResponseObject, error)
	// Get capture details
	// (GET /api/v1/captures/{captureId})
	GetCapture(ctx context.Context, request GetCaptureRequestObject) (GetCaptureResponseObject, error)
	// Refund capture
	// (POST /api/v1/refunds)
	CreateRefund(ctx context.Context, request CreateRefundRequestObject) (CreateRefundResponseObject, error)
	// Get refund details
	// (GET /api/v1/refunds/{refundId})
	GetRefund(ctx context.Context, request GetRefundRequestObject) (GetRefundResponseObject, error)
	// Void authorization
	// (POST /api/v1/voids)
	CreateVoid(ctx context.Context, request CreateVoidRequestObject) (CreateVoidResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateAuthorization operation middleware
func (sh *strictHandler) CreateAuthorization(w http.ResponseWriter, r *http.Request, params CreateAuthorizationParams) {
	var request CreateAuthorizationRequestObject

	request.Params = params

	var body CreateAuthorizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAuthorization(ctx, request.(CreateAuthorizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAuthorization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAuthorizationResponseObject); ok {
		if err := validResponse.VisitCreateAuthorizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthorization operation middleware
func (sh *strictHandler) GetAuthorization(w http.ResponseWriter, r *http.Request, authorizationId AuthorizationId) {
	var request GetAuthorizationRequestObject

	request.AuthorizationId = authorizationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthorization(ctx, request.(GetAuthorizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthorization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthorizationResponseObject); ok {
		if err := validResponse.VisitGetAuthorizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCapture operation middleware
func (sh *strictHandler) CreateCapture(w http.ResponseWriter, r *http.Request, params CreateCaptureParams) {
	var request CreateCaptureRequestObject

	request.Params = params

	var body CreateCaptureJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCapture(ctx, request.(CreateCaptureRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCapture")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCaptureResponseObject); ok {
		if err := validResponse.VisitCreateCaptureResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCapture operation middleware
func (sh *strictHandler) GetCapture(w http.ResponseWriter, r *http.Request, captureId CaptureId) {
	var request GetCaptureRequestObject

	request.CaptureId = captureId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCapture(ctx, request.(GetCaptureRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCapture")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCaptureResponseObject); ok {
		if err := validResponse.VisitGetCaptureResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRefund operation middleware
func (sh *strictHandler) CreateRefund(w http.ResponseWriter, r *http.Request, params CreateRefundParams) {
	var request CreateRefundRequestObject

	request.Params = params

	var body CreateRefundJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRefund(ctx, request.(CreateRefundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRefund")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRefundResponseObject); ok {
		if err := validResponse.VisitCreateRefundResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRefund operation middleware
func (sh *strictHandler) GetRefund(w http.ResponseWriter, r *http.Request, refundId RefundId) {
	var request GetRefundRequestObject

	request.RefundId = refundId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRefund(ctx, request.(GetRefundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRefund")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRefundResponseObject); ok {
		if err := validResponse.VisitGetRefundResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateVoid operation middleware
func (sh *strictHandler) CreateVoid(w http.ResponseWriter, r *http.Request, params CreateVoidParams) {
	var request CreateVoidRequestObject

	request.Params = params

	var body CreateVoidJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVoid(ctx, request.(CreateVoidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVoid")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateVoidResponseObject); ok {
		if err := validResponse.VisitCreateVoidResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
