// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Ra63PbuBH/VzDodSaZoSzq5Yv0Lcm1V8+lrce5y5fY1UDkSsSZBHgAKEf16H/vAOAL",
	"FPRw/Lj6G1/YXez+9gne44hnOWfAlMSze5wTQTJQIMzd+0IlXND/EkU5u4j1oxhkJGiuH+CZ+wG6+Am9",
	"WXKREYVIoZL5dRGGo6goaGyu4C0OMNXLcqISHGBGMsAzTDpcAizgj4IKiPFMiQICLKMEMmLlUwqEpvEf",
	"w+Jr2JuS3vLm/t22V1+PT7geDLc/4ACrTa5FkEpQtsLbbYA/klwVAny7LV+19xmR/NRtRjXhEzeoaT/9",
	"/i5iyHKugEWbX2BzVQvS3exvjP5RALqFDVpygWi1TCEtPEgl0ZuMfEPDyQRFCRGy3nYCJAbRbLzFsfcL",
	"bA5uPyPfPgFbqQTPhpNJgDPKqvuBbzdXsCxY7DOWfdO2lYDlqbYSFdkTTaVJP7Wptpq3zDmTYJzxA4mv",
	"rOb1XcSZNoa+JHme0sh4T/93qTd/35LyBwFLPMN/6TeO3rdvZf9vQnBxVTKxLF0lfiEpja1zc4EWhaQM",
	"pEQpX9EIgV6NNaSY1gNJDbmXE65iiySINYhGnn9x9XdesPjlRLkCyQsRAWJcoaXhvQ3wJdlkwFTbx15K",
	"M7JYLmlEtbtqJEvjLOX6nchek9KgFjwHoajFHMl4YaWFbyTLU8Cz6XQ6DbB1KTzDlKnzcYNeyhSswFjB",
	"CetzGjtUzNv5ZBLCu3EY9mA4XfTGg3jcIz8Oznvj8fn5ZDIeh2EY7npGgCMBREE8J0a0WpaYKOgpmoF3",
	"TSGEDkGuGL99/sn3MXzLqQD5IAZSEVUYrQErMjz7qi0s+BpifOMLXU1g+bqrq5pcUNmgtQNHPkcbDSO+",
	"+B0ihZuE9vqMbOXeIarT4gk0BwdoPiNydlFQ8TyOgtaOgwdDor01LwwMSjp+X6eTfYjolHvmOaIMRaZg",
	"DI4iJqOMZloPAx96IiLiOSuyBQhftSViZF+iN5+KhKG1zUYQv21zxuPJaBgOJoPB8N0oHJ2fa7ZNGTGY",
	"ulXEKGgn7uvr+H4wCgZTXwoOcLRe7xFsDYIuy/CtBSvAkWkwHLlijB0pdoUYBWO/CMbVN/OMM72whcDB",
	"0DAo1Ts8puuSzgaIcMgMw+GkRWgYTqctUsNwON6ltoPbxoxWZx2xXe41fvfDtI5ZjwMoepMVUqGMqChB",
	"jkO9fTR2fZHvSHOkOCq91MHKQ6Lk8/c/R9LSUdPZuvtJLVcq7e0TxJt2Stnb3CmObAPgmOnEvNOx0vM0",
	"cfuzxjHzfOH0gHG+C9NrTuPXCmifokx5/ZHH0M7ilJnsM9exzvSM5a0JdtVdk5d1RLRFmv26qcfnth7X",
	"UJWSstWcNu3x/Na0x66UjKu5bSm6bxoG7nOSCiDxZl5I+7K8rQuR5pE2nfPA4h4aKM0zKo0XNiWGI5Fd",
	"4DxqX9OyR5vb5uzGk+DcbmYHk1A1lUc7ImOybYAzkJKswC3X3q8JTckiBbQgKWERICpRqptZlRBWzTQg",
	"RrUNDyPJitUw8wHpH0BSlezf2m6tmJgVGgMFq66Plo0lGZ8EVTB+jtL/Werzh5TaJfS6/AUsT+E/2k/y",
	"gf3BrhlrLzpqu2YPgRvID9b6bTF9ZrdBfq/Rn69n21VFGWF8jq9f7bA3D09gP8R7KD7IeB1rVBId7r4a",
	"Lru61xQpW/LdzPlrQqWOOQRlPLpFC8Ju0fvLCzNcze2gCK2IgjuyQcbLhM2xCqSibHV2zS4UkjQrUqJA",
	"Ip1h3JI2qOqkwGTkABEWl3UM0uY3H8mza2YkMUJ8qITIBV/TGCRaEEkjtCxYpL8mKVUbneK1ELWUy5Tf",
	"SXRHVcILhQSQFGWcwQYpQZgkUcXnmr1PU3T578+/ImBxzqmu60p1I8JQZy6M7Nz47JpN/or4shkz39E0",
	"RYKwmGfpBi0JTQ1zNAlDO/PTzDSrekVC1oAo0yaBGGmFsWiDFqDuABgahGFvGIZhptdpTFBloGe08U+t",
	"l/eXF9rOIKS13eAsPAs1wHgOjOQUz/DoLDwb2folMYDvk5z214O+YxN7psKlp+C9TEkErgVRwtMYcYZI",
	"FJlq2JQKZ9jwFfUhjK+VN5I0Rzdf/emy+aS/5xhge2M9AqT6wOPNk40sD0wftq4XKlFAd/Q9DMMnk8Q/",
	"+fQMUd1StxyyaRCMrTQ+JrXU/da03iwZHl/SHRdvAzw5hZU7fjeD3iLLiNjUUPHATOOerDRU3I3iG03A",
	"D+b+feeobquFW4GxiAvRn0E9Dp/do0cLzP8vTNSD/nE4Pm6m+lTCtdDPoDrmiUERmsrTLFTG/AOBpmps",
	"CcoFrCkvZLqpOUJs0HCGyv5737xkXxD6WM8zXkH46UyVXjjwdOfwHnhVpnpcsHl80KgQ0/HgCo6V0b1A",
	"7N/XB90Hw8P3Iqc5n3/WkPAAaz1ZGCgV5wkAXo3b2u6A55dH4KQiHFclnM/dy2/2OfpVNRB7BX7ujiBf",
	"2M07Lbf3sNiY5U928kqK2g0rrJWW9kGtf1/9GHHQtb8TK/W/HM/q2Cfb58ncuuzBdr3ap2nduh1M5iyC",
	"VHdPns5hAUuus8dhT/5ix7WvwI/bs+oX9mJnguL7MYbTP92DjQz7crSxskWWHSQeclg7qMTPqM/OKNSj",
	"UfsFKqcsRj+jF2T/GcSaRoAKRqpJcUfdpYBRAtFtS9Gl7m4MTfsnkvUol/4nHpEUxbCGlOdmjGK/xQEu",
	"RIpnOFEqn/X7qf4u4VLN3v347kfjYCWne7/CCItLpTVTluZHtlK6beA9xHZjSDMkata7nccumbJnrUsX",
	"H42qeNld7bZTOvR5CRgs766+6s62mhVlZN3ebP8XAAD//5hqSvvhKgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
