// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benx421/payment-gateway/bank/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRefunder is an autogenerated mock type for the Refunder type
type MockRefunder struct {
	mock.Mock
}

type MockRefunder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefunder) EXPECT() *MockRefunder_Expecter {
	return &MockRefunder_Expecter{mock: &_m.Mock}
}

// GetRefund provides a mock function with given fields: ctx, refundID
func (_m *MockRefunder) GetRefund(ctx context.Context, refundID uuid.UUID) (*models.Transaction, error) {
	ret := _m.Called(ctx, refundID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefund")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Transaction, error)); ok {
		return rf(ctx, refundID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Transaction); ok {
		r0 = rf(ctx, refundID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, refundID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefunder_GetRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefund'
type MockRefunder_GetRefund_Call struct {
	*mock.Call
}

// GetRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - refundID uuid.UUID
func (_e *MockRefunder_Expecter) GetRefund(ctx interface{}, refundID interface{}) *MockRefunder_GetRefund_Call {
	return &MockRefunder_GetRefund_Call{Call: _e.mock.On("GetRefund", ctx, refundID)}
}

func (_c *MockRefunder_GetRefund_Call) Run(run func(ctx context.Context, refundID uuid.UUID)) *MockRefunder_GetRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefunder_GetRefund_Call) Return(_a0 *models.Transaction, _a1 error) *MockRefunder_GetRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefunder_GetRefund_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Transaction, error)) *MockRefunder_GetRefund_Call {
	_c.Call.Return(run)
	return _c
}

// Refund provides a mock function with given fields: ctx, captureID, amount
func (_m *MockRefunder) Refund(ctx context.Context, captureID uuid.UUID, amount int64) (*models.Transaction, error) {
	ret := _m.Called(ctx, captureID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (*models.Transaction, error)); ok {
		return rf(ctx, captureID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) *models.Transaction); ok {
		r0 = rf(ctx, captureID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = rf(ctx, captureID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefunder_Refund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refund'
type MockRefunder_Refund_Call struct {
	*mock.Call
}

// Refund is a helper method to define mock.On call
//   - ctx context.Context
//   - captureID uuid.UUID
//   - amount int64
func (_e *MockRefunder_Expecter) Refund(ctx interface{}, captureID interface{}, amount interface{}) *MockRefunder_Refund_Call {
	return &MockRefunder_Refund_Call{Call: _e.mock.On("Refund", ctx, captureID, amount)}
}

func (_c *MockRefunder_Refund_Call) Run(run func(ctx context.Context, captureID uuid.UUID, amount int64)) *MockRefunder_Refund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *MockRefunder_Refund_Call) Return(_a0 *models.Transaction, _a1 error) *MockRefunder_Refund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefunder_Refund_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) (*models.Transaction, error)) *MockRefunder_Refund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefunder creates a new instance of MockRefunder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefunder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefunder {
	mock := &MockRefunder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
