// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benx421/payment-gateway/bank/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCapturer is an autogenerated mock type for the Capturer type
type MockCapturer struct {
	mock.Mock
}

type MockCapturer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCapturer) EXPECT() *MockCapturer_Expecter {
	return &MockCapturer_Expecter{mock: &_m.Mock}
}

// Capture provides a mock function with given fields: ctx, authorizationID, amount
func (_m *MockCapturer) Capture(ctx context.Context, authorizationID uuid.UUID, amount int64) (*models.Transaction, error) {
	ret := _m.Called(ctx, authorizationID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Capture")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (*models.Transaction, error)); ok {
		return rf(ctx, authorizationID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) *models.Transaction); ok {
		r0 = rf(ctx, authorizationID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = rf(ctx, authorizationID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCapturer_Capture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capture'
type MockCapturer_Capture_Call struct {
	*mock.Call
}

// Capture is a helper method to define mock.On call
//   - ctx context.Context
//   - authorizationID uuid.UUID
//   - amount int64
func (_e *MockCapturer_Expecter) Capture(ctx interface{}, authorizationID interface{}, amount interface{}) *MockCapturer_Capture_Call {
	return &MockCapturer_Capture_Call{Call: _e.mock.On("Capture", ctx, authorizationID, amount)}
}

func (_c *MockCapturer_Capture_Call) Run(run func(ctx context.Context, authorizationID uuid.UUID, amount int64)) *MockCapturer_Capture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *MockCapturer_Capture_Call) Return(_a0 *models.Transaction, _a1 error) *MockCapturer_Capture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCapturer_Capture_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) (*models.Transaction, error)) *MockCapturer_Capture_Call {
	_c.Call.Return(run)
	return _c
}

// GetCapture provides a mock function with given fields: ctx, captureID
func (_m *MockCapturer) GetCapture(ctx context.Context, captureID uuid.UUID) (*models.Transaction, error) {
	ret := _m.Called(ctx, captureID)

	if len(ret) == 0 {
		panic("no return value specified for GetCapture")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Transaction, error)); ok {
		return rf(ctx, captureID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Transaction); ok {
		r0 = rf(ctx, captureID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, captureID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCapturer_GetCapture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapture'
type MockCapturer_GetCapture_Call struct {
	*mock.Call
}

// GetCapture is a helper method to define mock.On call
//   - ctx context.Context
//   - captureID uuid.UUID
func (_e *MockCapturer_Expecter) GetCapture(ctx interface{}, captureID interface{}) *MockCapturer_GetCapture_Call {
	return &MockCapturer_GetCapture_Call{Call: _e.mock.On("GetCapture", ctx, captureID)}
}

func (_c *MockCapturer_GetCapture_Call) Run(run func(ctx context.Context, captureID uuid.UUID)) *MockCapturer_GetCapture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCapturer_GetCapture_Call) Return(_a0 *models.Transaction, _a1 error) *MockCapturer_GetCapture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCapturer_GetCapture_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Transaction, error)) *MockCapturer_GetCapture_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCapturer creates a new instance of MockCapturer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCapturer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCapturer {
	mock := &MockCapturer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
