// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benx421/payment-gateway/bank/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuthorizer is an autogenerated mock type for the Authorizer type
type MockAuthorizer struct {
	mock.Mock
}

type MockAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizer) EXPECT() *MockAuthorizer_Expecter {
	return &MockAuthorizer_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, cardNumber, cvv, amount
func (_m *MockAuthorizer) Authorize(ctx context.Context, cardNumber string, cvv string, amount int64) (*models.Transaction, error) {
	ret := _m.Called(ctx, cardNumber, cvv, amount)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) (*models.Transaction, error)); ok {
		return rf(ctx, cardNumber, cvv, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) *models.Transaction); ok {
		r0 = rf(ctx, cardNumber, cvv, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, cardNumber, cvv, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorizer_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockAuthorizer_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - cardNumber string
//   - cvv string
//   - amount int64
func (_e *MockAuthorizer_Expecter) Authorize(ctx interface{}, cardNumber interface{}, cvv interface{}, amount interface{}) *MockAuthorizer_Authorize_Call {
	return &MockAuthorizer_Authorize_Call{Call: _e.mock.On("Authorize", ctx, cardNumber, cvv, amount)}
}

func (_c *MockAuthorizer_Authorize_Call) Run(run func(ctx context.Context, cardNumber string, cvv string, amount int64)) *MockAuthorizer_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockAuthorizer_Authorize_Call) Return(_a0 *models.Transaction, _a1 error) *MockAuthorizer_Authorize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorizer_Authorize_Call) RunAndReturn(run func(context.Context, string, string, int64) (*models.Transaction, error)) *MockAuthorizer_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorization provides a mock function with given fields: ctx, authID
func (_m *MockAuthorizer) GetAuthorization(ctx context.Context, authID uuid.UUID) (*models.Transaction, error) {
	ret := _m.Called(ctx, authID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorization")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Transaction, error)); ok {
		return rf(ctx, authID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Transaction); ok {
		r0 = rf(ctx, authID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, authID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorizer_GetAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorization'
type MockAuthorizer_GetAuthorization_Call struct {
	*mock.Call
}

// GetAuthorization is a helper method to define mock.On call
//   - ctx context.Context
//   - authID uuid.UUID
func (_e *MockAuthorizer_Expecter) GetAuthorization(ctx interface{}, authID interface{}) *MockAuthorizer_GetAuthorization_Call {
	return &MockAuthorizer_GetAuthorization_Call{Call: _e.mock.On("GetAuthorization", ctx, authID)}
}

func (_c *MockAuthorizer_GetAuthorization_Call) Run(run func(ctx context.Context, authID uuid.UUID)) *MockAuthorizer_GetAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthorizer_GetAuthorization_Call) Return(_a0 *models.Transaction, _a1 error) *MockAuthorizer_GetAuthorization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorizer_GetAuthorization_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Transaction, error)) *MockAuthorizer_GetAuthorization_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorizer creates a new instance of MockAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizer {
	mock := &MockAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
