// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/benx421/payment-gateway/bank/internal/models"
)

// MockIdempotencyRepository is an autogenerated mock type for the IdempotencyRepository type
type MockIdempotencyRepository struct {
	mock.Mock
}

type MockIdempotencyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepository_Expecter {
	return &MockIdempotencyRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key, requestPath
func (_m *MockIdempotencyRepository) Get(ctx context.Context, key string, requestPath string) (*models.IdempotencyKey, error) {
	ret := _m.Called(ctx, key, requestPath)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.IdempotencyKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.IdempotencyKey, error)); ok {
		return rf(ctx, key, requestPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.IdempotencyKey); ok {
		r0 = rf(ctx, key, requestPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IdempotencyKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, requestPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdempotencyRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIdempotencyRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - requestPath string
func (_e *MockIdempotencyRepository_Expecter) Get(ctx interface{}, key interface{}, requestPath interface{}) *MockIdempotencyRepository_Get_Call {
	return &MockIdempotencyRepository_Get_Call{Call: _e.mock.On("Get", ctx, key, requestPath)}
}

func (_c *MockIdempotencyRepository_Get_Call) Run(run func(ctx context.Context, key string, requestPath string)) *MockIdempotencyRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIdempotencyRepository_Get_Call) Return(_a0 *models.IdempotencyKey, _a1 error) *MockIdempotencyRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdempotencyRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*models.IdempotencyKey, error)) *MockIdempotencyRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, idemKey
func (_m *MockIdempotencyRepository) Store(ctx context.Context, idemKey *models.IdempotencyKey) error {
	ret := _m.Called(ctx, idemKey)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.IdempotencyKey) error); ok {
		r0 = rf(ctx, idemKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIdempotencyRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockIdempotencyRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - idemKey *models.IdempotencyKey
func (_e *MockIdempotencyRepository_Expecter) Store(ctx interface{}, idemKey interface{}) *MockIdempotencyRepository_Store_Call {
	return &MockIdempotencyRepository_Store_Call{Call: _e.mock.On("Store", ctx, idemKey)}
}

func (_c *MockIdempotencyRepository_Store_Call) Run(run func(ctx context.Context, idemKey *models.IdempotencyKey)) *MockIdempotencyRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.IdempotencyKey))
	})
	return _c
}

func (_c *MockIdempotencyRepository_Store_Call) Return(_a0 error) *MockIdempotencyRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdempotencyRepository_Store_Call) RunAndReturn(run func(context.Context, *models.IdempotencyKey) error) *MockIdempotencyRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdempotencyRepository creates a new instance of MockIdempotencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
