// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benx421/payment-gateway/bank/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockVoider is an autogenerated mock type for the Voider type
type MockVoider struct {
	mock.Mock
}

type MockVoider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVoider) EXPECT() *MockVoider_Expecter {
	return &MockVoider_Expecter{mock: &_m.Mock}
}

// Void provides a mock function with given fields: ctx, authorizationID
func (_m *MockVoider) Void(ctx context.Context, authorizationID uuid.UUID) (*models.Transaction, error) {
	ret := _m.Called(ctx, authorizationID)

	if len(ret) == 0 {
		panic("no return value specified for Void")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Transaction, error)); ok {
		return rf(ctx, authorizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Transaction); ok {
		r0 = rf(ctx, authorizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, authorizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVoider_Void_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Void'
type MockVoider_Void_Call struct {
	*mock.Call
}

// Void is a helper method to define mock.On call
//   - ctx context.Context
//   - authorizationID uuid.UUID
func (_e *MockVoider_Expecter) Void(ctx interface{}, authorizationID interface{}) *MockVoider_Void_Call {
	return &MockVoider_Void_Call{Call: _e.mock.On("Void", ctx, authorizationID)}
}

func (_c *MockVoider_Void_Call) Run(run func(ctx context.Context, authorizationID uuid.UUID)) *MockVoider_Void_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVoider_Void_Call) Return(_a0 *models.Transaction, _a1 error) *MockVoider_Void_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVoider_Void_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Transaction, error)) *MockVoider_Void_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVoider creates a new instance of MockVoider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVoider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVoider {
	mock := &MockVoider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
